### ISSUE TITLE
Non open-source models

### ISSUE THREAD

**Issue by sarthak405** [aounon/llm-rank-optimizer#2]
Is it possible to optimize the STS for a product for a non-open-source model with only an inferencing endpoint, say GPT-4?

**Comment by davidrzs** [comment]
Hi @sarthak405 

Not directly. The optimization procedure relies on having white box access to the model, as we need a gradient to sample suitable tokens for the STS. However, we do show that our attack translates over to non-open-source models by jointly optimizing over multiple open source models and then using the found STS on API access only models. (some results of this can be found in this repo in the transfer folders).

If you want to learn more about how the optimization, I recommend checking out https://arxiv.org/pdf/2307.15043 where they have detailed results on the transferability of gradient based attacks. 
While there are some methods that could work on black box access only out of personal experience using GCG on white box and then translating over to black box works quite well.
